package com.example.aitestgen.bonus;

import com.example.aitestgen.model.TestCaseResponse;
import com.example.aitestgen.model.TestScenario;

import java.util.List;
import java.util.stream.Collectors;

/**
 * BONUS MODULE: Selenium Skeleton Generator
 *
 * Converts automation-candidate test scenarios into
 * a Selenium TestNG skeleton code stub.
 *
 * This module demonstrates how the generated test cases
 * can be wired into actual Selenium automation with Page Objects.
 *
 * Note: This generates CODE STUBS only — actual selectors
 * and page object implementations would need to be added manually.
 *
 * Usage:
 *   SeleniumSkeletonGenerator gen = new SeleniumSkeletonGenerator();
 *   String skeleton = gen.generateSkeleton(response);
 *   FileUtils.writeFile("output/SeleniumTests.java", skeleton);
 */
public class SeleniumSkeletonGenerator {

    /**
     * Generates a complete Selenium TestNG class skeleton
     * for all automation_candidate=true test scenarios.
     *
     * @param response The normalized TestCaseResponse.
     * @return Java source code as a String.
     */
    public String generateSkeleton(TestCaseResponse response) {
        if (response == null || response.getTestScenarios() == null) {
            return "// No test scenarios available for skeleton generation.";
        }

        List<TestScenario> automationCandidates = response.getTestScenarios().stream()
                .filter(TestScenario::isAutomationCandidate)
                .collect(Collectors.toList());

        if (automationCandidates.isEmpty()) {
            return "// No automation-candidate scenarios found in the generated test cases.";
        }

        StringBuilder sb = new StringBuilder();

        // File header
        sb.append("package com.example.tests;\n\n");
        sb.append("import org.openqa.selenium.WebDriver;\n");
        sb.append("import org.openqa.selenium.chrome.ChromeDriver;\n");
        sb.append("import org.testng.Assert;\n");
        sb.append("import org.testng.annotations.*;\n\n");

        // Class javadoc
        sb.append("/**\n");
        sb.append(" * AUTO-GENERATED Selenium TestNG Skeleton\n");
        sb.append(" * Feature: ").append(response.getFeatureName()).append("\n");
        sb.append(" * Generated by: AI Test Case Generator\n");
        sb.append(" *\n");
        sb.append(" * ⚠️  THIS IS A SKELETON — Implement page object methods before running.\n");
        sb.append(" */\n");

        // Class definition
        String className = toClassName(response.getFeatureName()) + "Tests";
        sb.append("public class ").append(className).append(" {\n\n");

        // WebDriver field
        sb.append("    private WebDriver driver;\n\n");

        // @BeforeMethod
        sb.append("    @BeforeMethod\n");
        sb.append("    public void setUp() {\n");
        sb.append("        // TODO: Set WebDriver path via WebDriverManager or System.setProperty\n");
        sb.append("        driver = new ChromeDriver();\n");
        sb.append("        driver.manage().window().maximize();\n");
        sb.append("        driver.get(\"https://your-app-url.com\"); // TODO: Replace with actual URL\n");
        sb.append("    }\n\n");

        // @AfterMethod
        sb.append("    @AfterMethod\n");
        sb.append("    public void tearDown() {\n");
        sb.append("        if (driver != null) {\n");
        sb.append("            driver.quit();\n");
        sb.append("        }\n");
        sb.append("    }\n\n");

        // Generate a @Test method for each automation candidate
        for (TestScenario scenario : automationCandidates) {
            sb.append(generateTestMethod(scenario));
            sb.append("\n");
        }

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * Generates a single @Test method block for a scenario.
     */
    private String generateTestMethod(TestScenario scenario) {
        StringBuilder sb = new StringBuilder();

        String methodName = toMethodName(scenario.getTitle());

        sb.append("    /**\n");
        sb.append("     * ").append(scenario.getTestCaseId()).append(": ").append(scenario.getTitle()).append("\n");
        sb.append("     * Objective: ").append(scenario.getObjective()).append("\n");
        sb.append("     * Priority: ").append(scenario.getPriority()).append("\n");
        sb.append("     * Type: ").append(scenario.getType()).append("\n");
        sb.append("     * Negative: ").append(scenario.isNegative()).append("\n");
        sb.append("     */\n");
        sb.append("    @Test(description = \"").append(escapeQuotes(scenario.getTitle())).append("\"");

        // Add groups based on type
        sb.append(", groups = {\"").append(scenario.getType().replace(" ", "_").toLowerCase()).append("\"");
        if (scenario.getPriority().equals("High")) sb.append(", \"smoke\"");
        sb.append("})\n");

        sb.append("    public void ").append(methodName).append("() {\n");

        // Preconditions as comments
        if (scenario.getPreconditions() != null) {
            sb.append("        // Preconditions:\n");
            scenario.getPreconditions().forEach(p ->
                    sb.append("        //   - ").append(p).append("\n"));
        }

        sb.append("\n");

        // Test steps as TODO comments
        if (scenario.getTestSteps() != null) {
            sb.append("        // Test Steps:\n");
            for (int i = 0; i < scenario.getTestSteps().size(); i++) {
                String step = scenario.getTestSteps().get(i);
                sb.append("        // Step ").append(i + 1).append(": ").append(step).append("\n");
                sb.append("        // TODO: Implement - pageObject.").append(toMethodName(step)).append("();\n");
            }
        }

        sb.append("\n");

        // Test data as comments
        if (scenario.getTestData() != null) {
            sb.append("        // Test Data: ").append(scenario.getTestData().getInput()).append("\n");
        }

        sb.append("\n");

        // Expected result as assertion stub
        sb.append("        // Expected: ").append(scenario.getExpectedResult()).append("\n");
        sb.append("        // TODO: Add assertion — e.g.:\n");
        sb.append("        // Assert.assertTrue(condition, \"").append(escapeQuotes(scenario.getExpectedResult())).append("\");\n");

        sb.append("    }\n");

        return sb.toString();
    }

    /**
     * Converts a feature/class name to a valid Java class name.
     * Example: "User Login" → "UserLogin"
     */
    private String toClassName(String name) {
        if (name == null || name.isBlank()) return "GeneratedTest";
        return name.trim()
                .replaceAll("[^a-zA-Z0-9 ]", "")
                .replaceAll("\\s+", " ")
                .chars()
                .collect(StringBuilder::new,
                        (sb, ch) -> {
                            if (sb.length() == 0 || sb.charAt(sb.length() - 1) == ' ') {
                                sb.append(Character.toUpperCase((char) ch));
                            } else {
                                if (ch != ' ') sb.append((char) ch);
                            }
                        },
                        StringBuilder::append)
                .toString();
    }

    /**
     * Converts a test title to a valid Java method name (camelCase).
     * Example: "Login with valid credentials" → "loginWithValidCredentials"
     */
    private String toMethodName(String title) {
        if (title == null || title.isBlank()) return "test";
        String[] words = title.trim()
                .replaceAll("[^a-zA-Z0-9 ]", "")
                .toLowerCase()
                .split("\\s+");

        StringBuilder sb = new StringBuilder(words[0]);
        for (int i = 1; i < words.length; i++) {
            if (!words[i].isEmpty()) {
                sb.append(Character.toUpperCase(words[i].charAt(0)));
                sb.append(words[i].substring(1));
            }
        }
        // Ensure it doesn't start with a digit
        if (Character.isDigit(sb.charAt(0))) {
            sb.insert(0, "test");
        }
        return sb.toString();
    }

    /**
     * Escapes double-quote characters for use inside Java string literals.
     */
    private String escapeQuotes(String input) {
        if (input == null) return "";
        return input.replace("\"", "\\\"");
    }
}
